INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Marek', 2);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Martina', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Spiderling', 1);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Hercules', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Bartimaeus', 2);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Nautilus', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Elissandra', 1);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Salamandra', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Kerberos', 2);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Kerbal', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('ET Mimozemstan', 1);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Chuck Norris', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Coraline', 2);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Petra Adamek', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Adka', 21);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Xera', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Santa Claus', 2);
INSERT INTO hero (hero_name, hero_level) VALUES ('Canny', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Homer Simpson', 1);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Bubbles', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('James Bond', 2);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Ribana', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Vinnetou', 1);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Blossom', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Buttercup', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Duffman', 2);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Sindibad', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Achyles', 1);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Spongebob', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Shrek', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Jerry', 2);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Sauron', 10);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Gandalf', 1);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Dumbledore', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Janka Odnaproti', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Shaggy', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Wilma', 5);
INSERT INTO hero (missionId, hero_name, hero_level) VALUES ('Welma', 5);



INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('Mission impossible', 2, 6, true);
INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('Mission possible', 8, 2, false);
INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('Dragon slayer', 2, 6, true);
INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('Spirit hunter', 8, 2, false);
INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('Light finder', 2, 6, true);
INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('Per aspera ad astra', 8, 2, false);
INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('Freedom fighter', 2, 6, true);
INSERT INTO mission(mission_name, level_required, capacity, available) VALUES ('The truth seeker', 8, 2, false);